import mongoose from "mongoose";

const directionSchema = new mongoose.Schema({
    north1: { type: String, default: "" },
    east1: { type: String, default: "" },
    south1: { type: String, default: "" },
    west1: { type: String, default: "" },
    north2: { type: String, default: "" },
    east2: { type: String, default: "" },
    south2: { type: String, default: "" },
    west2: { type: String, default: "" }
}, { _id: false });

const coordinateSchema = new mongoose.Schema({
    latitude: { type: String, default: "" },
    longitude: { type: String, default: "" }
}, { _id: false });

const photoSchema = new mongoose.Schema({
    elevationImages: [String],
    siteImages: [String]
}, { _id: false });

const pdfDetailsSchema = new mongoose.Schema({
    // GENERAL TAB FIELDS
    numberingFlatBungalowPlotNo: { type: String, default: "" },
    applicant: { type: String, default: "" },
    nameOfOwnerOrOwners: { type: String, default: "" },
    ownerNameAddress: { type: String, default: "" },
    typeOfProperty: { type: String, default: "" },
    typeOfStructure: { type: String, default: "" },
    structureType: { type: String, default: "" },
    statusOfTenure: { type: String, default: "" },
    accountName: { type: String, default: "" },
    nameOfOwner: { type: String, default: "" },
    client: { type: String, default: "" },
    borrowerAccountName: { type: String, default: "" },
    mobileNo: { type: String, default: "" },
    mobileNumber: { type: String, default: "" },
    contactNumberOfRepresentative: { type: String, default: "" },
    nearbyLandmarkGoogleMap: { type: String, default: "" },
    latitudeLongitude: { type: String, default: "" },
    postalAddress: { type: String, default: "" },
    matchingOfBoundaries: { type: String, default: "" },
    boundariesOfPropertyProperDemarcation: { type: String, default: "" },
    independentAccessToProperty: { type: String, default: "" },
    addressOfPropertyUnderValuation: { type: String, default: "" },
    place: { type: String, default: "" },
    referenceNo: { type: String, default: "" },
    adjoiningPropertiesNorthDocument: { type: String, default: "" },
    adjoiningPropertiesNorthSite: { type: String, default: "" },
    adjoiningPropertiesSouthDocument: { type: String, default: "" },
    adjoiningPropertiesSouthSite: { type: String, default: "" },
    adjoiningPropertiesEastDocument: { type: String, default: "" },
    adjoiningPropertiesEastSite: { type: String, default: "" },
    adjoiningPropertiesWestDocument: { type: String, default: "" },
    adjoiningPropertiesWestSite: { type: String, default: "" },
    plotDemarcated: { type: String, default: "" },
    dateOfInspectionOfProperty: { type: String, default: "" },
    inspectedBy: { type: String, default: "" },
    engagementLetterConfirmation: { type: String, default: "" },
    ownershipDocumentsSaleDeed: { type: String, default: "" },
    allotmentLetter: { type: String, default: "" },
    approvedPlan: { type: String, default: "" },
    briefDescriptionOfProperty: { type: String, default: "" },
    ageOfPropertyInYears: { type: String, default: "" },
    stageOfConstruction: { type: String, default: "" },
    mergedProperty: { type: String, default: "" },
    premiseCanBeSeparatedEntrance: { type: String, default: "" },
    propertyIsRentedToOtherParty: { type: String, default: "" },
    landIsLocked: { type: String, default: "" },
    ifRentedRentAgreementProvided: { type: String, default: "" },
    violationsIfAnyObserved: { type: String, default: "" },
    approvedLandUse: { type: String, default: "" },
    noOfYearsOfOccupancySince: { type: String, default: "" },
    relationshipOfTenantOrOwner: { type: String, default: "" },
    natureAndExtentOfViolations: { type: String, default: "" },
    propertyDetails: { type: String, default: "" },
    remarks: { type: String, default: "" },

    // VALUATION TAB FIELDS
    purposeOfValuation: { type: String, default: "" },
    purposeOfProperty: { type: String, default: "" },
    valuationDoneByGovtApprovedValuer: { type: String, default: "" },
    dateOfValuation: { type: String, default: "" },
    dateOfInspection: { type: String, default: "" },
    date: { type: String, default: "" },
    dateOfValuationReport: { type: String, default: "" },
    valuationMadeDate: { type: String, default: "" },
    areaOfLand: { type: String, default: "" },
    areaOfConstruction: { type: String, default: "" },
    revenueDetailsPerSaleDeed: { type: String, default: "" },
    landAreaPerSaleDeed: { type: String, default: "" },
    landAreaAsPerSaleDeed: { type: String, default: "" },
    landAreaAsPerGRUDA: { type: String, default: "" },
    builtUpAreaAsPerGRUDA: { type: String, default: "" },
    builtUpAreaPerGrudaImpactPlan: { type: String, default: "" },
    cabuaSbuaInSqFt: { type: String, default: "" },
    yearOfConstruction: { type: String, default: "" },
    yearConstruction: { type: String, default: "" },
    totalLifeOfPropertyInYears: { type: String, default: "" },
    ifUnderConstructionExtentOfCompletion: { type: String, default: "" },
    residualAgeOfPropertyInYears: { type: String, default: "" },
    totalNoOfFloor: { type: String, default: "" },
    numberOfFloors: { type: String, default: "" },
    floorOnWhichPropertyIsLocated: { type: String, default: "" },
    noOfRoomsLivingDining: { type: String, default: "" },
    bedRooms: { type: String, default: "" },
    noOfRoomsToiletBath: { type: String, default: "" },
    kitchenStore: { type: String, default: "" },
    location: { type: String, default: "" },
    valueOfLand: { type: String, default: "" },
    valueOfConstruction: { type: String, default: "" },
    totalMarketValueOfProperty: { type: String, default: "" },
    realisableValue: { type: String, default: "" },
    realizableValue: { type: String, default: "" },
    distressSaleValue: { type: String, default: "" },
    distressValue: { type: String, default: "" },
    insurableValueOfProperty: { type: String, default: "" },
    insurableValue: { type: String, default: "" },
    jantriValueOfProperty: { type: String, default: "" },
    realisableValuePercentage: { type: String, default: "" },
    distressValuePercentage: { type: String, default: "" },
    buildingValueEstimatedReplacementRate: { type: String, default: "" },
    bookValueOfProperty: { type: String, default: "" },
    bookValueAsPerSaleDeed: { type: String, default: "" },
    saleDeedRegistrationNumber: { type: String, default: "" },
    saleDeedDate: { type: String, default: "" },
    valuersOpinion: { type: String, default: "" },
    valuationBy: { type: String, default: "" },
    guidelineRateObtainedFrom: { type: String, default: "" },
    jantriRatePerSqMt: { type: String, default: "" },
    revisedGuidelineRate: { type: String, default: "" },
    jantriValueOfLand: { type: String, default: "" },
    guidelineValue: { type: String, default: "" },
    marketValueOfProperty: { type: String, default: "" },
    dateOfReport: { type: String, default: "" },
    inspectionDate: { type: String, default: "" },
    saleDeed: { type: String, default: "" },
    grudaImpactPlan: { type: String, default: "" },
    layoutPlan: { type: String, default: "" },
    constructionPermission: { type: String, default: "" },
    lightBill: { type: String, default: "" },
    taxBill: { type: String, default: "" },

    // VALUATION ANALYSIS TAB FIELDS
    landAreaSFT: { type: String, default: "" },
    landRate: { type: String, default: "" },
    landRatePerSqFt: { type: String, default: "" },
    valueOfLand: { type: String, default: "" },
    valueOfLandPerSqFt: { type: String, default: "" },
    totalLandValue: { type: String, default: "" },
    totalBUA: { type: String, default: "" },
    plinthArea: { type: String, default: "" },
    roofHeight: { type: String, default: "" },
    ageOfBuilding: { type: String, default: "" },
    estimatedReplacementRate: { type: String, default: "" },
    valueOfConstruction: { type: String, default: "" },
    dataSheet: { type: String, default: "" },
    buildingValuePlinthArea: { type: String, default: "" },
    buildingValueRoofHeight: { type: String, default: "" },
    buildingValueAge: { type: String, default: "" },
    buildingValueOfConstruction: { type: String, default: "" },
    totalBuildingValue: { type: String, default: "" },
    fairMarketValueInWords: { type: String, default: "" },
    realisableValueInWords: { type: String, default: "" },
    distressValueInWords: { type: String, default: "" },
    dateOfVisit: { type: String, default: "" },
    valuationReportDeclaration: { type: String, default: "" },
    propertyInspectionDeclaration: { type: String, default: "" },
    siteVisitPhotos: { type: String, default: "" },
    selfieWithOwner: { type: String, default: "" },
    selfieWithOwnerIdentifier: { type: String, default: "" },
    mobileNo: { type: String, default: "" },
    saleInstanceLocalInquiry: { type: String, default: "" },
    brokerRecording: { type: String, default: "" },
    advTcrLsr: { type: String, default: "" },
    kabulatLekh: { type: String, default: "" },
    mortgageDeed: { type: String, default: "" },
    leaseDeed: { type: String, default: "" },
    index2: { type: String, default: "" },
    vf712InCaseOfLand: { type: String, default: "" },
    naOrder: { type: String, default: "" },
    commencementLetter: { type: String, default: "" },
    buPermission: { type: String, default: "" },
    tentativeRate: { type: String, default: "" },
    pastValuationRate: { type: String, default: "" },
    subContractingDeclaration: { type: String, default: "" },
    eleMeterPhoto: { type: String, default: "" },
    muniTaxBill: { type: String, default: "" },
    numberingFlatPlotNoIdentification: { type: String, default: "" },
    dataSheet: { type: String, default: "" },

    // CHECKLIST FIELDS (Yes/No dropdowns)
    checklist_engagementLetterConfirmation: { type: String, default: "" },
    checklist_ownershipDocumentsSaleDeed: { type: String, default: "" },
    checklist_advTcrLsr: { type: String, default: "" },
    checklist_allotmentLetter: { type: String, default: "" },
    checklist_kabulatLekh: { type: String, default: "" },
    checklist_mortgageDeed: { type: String, default: "" },
    checklist_leaseDeed: { type: String, default: "" },
    checklist_index2: { type: String, default: "" },
    checklist_vf712InCaseOfLand: { type: String, default: "" },
    checklist_naOrder: { type: String, default: "" },
    checklist_approvedPlan: { type: String, default: "" },
    checklist_commencementLetter: { type: String, default: "" },
    checklist_buPermission: { type: String, default: "" },
    checklist_eleMeterPhoto: { type: String, default: "" },
    checklist_lightBill: { type: String, default: "" },
    checklist_muniTaxBill: { type: String, default: "" },
    checklist_numberingFlatPlotNoIdentification: { type: String, default: "" },
    checklist_boundariesPropertyDemarcation: { type: String, default: "" },
    checklist_mergedProperty: { type: String, default: "" },
    checklist_premiseCanBeSeparatedEntrance: { type: String, default: "" },
    checklist_landIsLocked: { type: String, default: "" },
    checklist_propertyIsRentedToOtherParty: { type: String, default: "" },
    checklist_ifRentedRentAgreementProvided: { type: String, default: "" },
    checklist_siteVisitPhotos: { type: String, default: "" },
    checklist_selfieWithOwnerIdentifier: { type: String, default: "" },
    checklist_mobileNo: { type: String, default: "" },
    checklist_dataSheet: { type: String, default: "" },
    checklist_tentativeRate: { type: String, default: "" },
    checklist_saleInstanceLocalInquiry: { type: String, default: "" },
    checklist_brokerRecording: { type: String, default: "" },
    checklist_pastValuationRate: { type: String, default: "" },

    // ASSUMPTIONS & REMARKS
    qualificationsInTIR: { type: String, default: "" },
    propertyIsSARFAESICompliant: { type: String, default: "" },
    propertyBelongsToSocialInfrastructure: { type: String, default: "" },
    entireLandMortgaged: { type: String, default: "" },
    anyOtherAspectOnMarketability: { type: String, default: "" },

    // ENCLOSURES
    layoutPlanSketch: { type: String, default: "" },
    buildingPlan: { type: String, default: "" },
    floorPlan: { type: String, default: "" },
    photographsOfProperty: { type: String, default: "" },
    certifiedCopyOfApprovedPlan: { type: String, default: "" },
    googleMapLocation: { type: String, default: "" },
    priceTrendFromPropertySites: { type: String, default: "" },
    anyOtherRelevantDocuments: { type: String, default: "" },
    
    // DYNAMIC DECLARATION TABLE FIELDS
    backgroundInfoComment: { type: String, default: "Referred provided documents" },
    valuationPurposeComment: { type: String, default: "Continue Financial Assistance Purpose" },
    valuersIdentityComment: { type: String, default: "Self-assessment" },
    conflictOfInterestComment: { type: String, default: "N.A." },
    inspectionsUndertakenComment: { type: String, default: "Yes." },
    informationSourcesComment: { type: String, default: "Local inquiries, brokers, known websites, i.e., matches, 99acre, propertiwalai, proptiger, housing, etc., if available" },
    valuationProceduresComment: { type: String, default: "Land & Building Method, with Market Approach for Land and Cost Approach for Building." },
    restrictionsOnUseComment: { type: String, default: "As per purpose mentioned in report." },
    majorFactorsComment: { type: String, default: "Location of the property, with developing of surroundings, for going-purpose valuation" },
    notConsideredFactorsComment: { type: String, default: "Future market events and Government Policies." },
    caveatsLimitationsComment: { type: String, default: "We are not responsible for Title of the subjected property and valuations affected by the same" },
   
}, { _id: false });
const customFieldSchema = new mongoose.Schema({
    name: { type: String, required: true },
    value: { type: String, required: true }
}, { _id: false });
const rajeshRowHouseSchema = new mongoose.Schema({
    clientId: { type: String, required: true, index: true },
    uniqueId: { type: String, required: true, sparse: true },
    username: { type: String, required: true },
    dateTime: { type: String, required: true },
    day: { type: String, required: true },
    bankName: { type: String, required: true },
    city: { type: String, required: true },
    clientName: { type: String, required: true },
    mobileNumber: { type: String, required: true },
    address: { type: String, required: true },
    payment: { type: String, required: true },
    collectedBy: { type: String, default: "" },
    dsa: { type: String, required: true },
    customDsa: { type: String, default: "" },
    engineerName: { type: String, required: true, default: "" }, 
    customEngineerName: { type: String, default: "" },
    notes: { type: String, default: "" },
    selectedForm: { type: String, default: null },
    elevation: { type: String, default: "" },
    directions: { type: directionSchema, default: () => ({}) },
    coordinates: { type: coordinateSchema, default: () => ({}) },
    propertyImages: [mongoose.Schema.Types.Mixed],
    locationImages: [mongoose.Schema.Types.Mixed],
     bankImage: { type: mongoose.Schema.Types.Mixed, default: null },
    documentPreviews: [mongoose.Schema.Types.Mixed],
    areaImages: { type: mongoose.Schema.Types.Mixed, default: () => ({}) },
    photos: { type: photoSchema, default: () => ({}) },
    bankImage: {
        url: { type: String, default: "" },
        fileName: { type: String, default: "" },
        size: { type: Number, default: 0 },
        path: { type: String, default: "" }
    },
    status: {
        type: String,
        enum: ["pending", "on-progress", "approved", "rejected", "rework"],
        default: "pending"
    },
    managerFeedback: { type: String, default: "" },
    submittedByManager: { type: Boolean, default: false }, 
    lastUpdatedBy: { type: String, default: "" },
    lastUpdatedByRole: { type: String, default: "" },
    pdfDetails: { type: pdfDetailsSchema, default: () => ({}) },
    customBankName: { type: String, default: "" },
    customCity: { type: String, default: "" },
    reworkComments: { type: String, default: "" },
    reworkRequestedBy: { type: String, default: "" },
    reworkRequestedAt: { type: Date, default: null },
    reworkRequestedByRole: { type: String, default: "" },
    lastUpdatedAt: { type: Date, default: Date.now },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },
 customFields: [{ type: customFieldSchema, default: () => ({}) }]

});

rajeshRowHouseSchema.index({ clientId: 1, uniqueId: 1 }, { unique: true, sparse: true });

// Indexes for faster queries
rajeshRowHouseSchema.index({ clientId: 1, username: 1 }); // For user-specific queries
rajeshRowHouseSchema.index({ clientId: 1, status: 1 }); // For status filtering
rajeshRowHouseSchema.index({ clientId: 1, createdAt: -1 }); // For sorting by creation date
rajeshRowHouseSchema.index({ clientId: 1, username: 1, status: 1 }); // For combined filtering

const RajeshRowHouseModel = mongoose.model("RajeshRowHouse", rajeshRowHouseSchema);
export default RajeshRowHouseModel;